% generate_elliptic_tests.m
%
% Generates elliptic_reference.hpp containing constexpr reference data
% for the constfilt Elliptic filter tests.
%
% Run from the octave/ directory:
%   octave --no-gui generate_elliptic_tests.m
%
% Requires: Signal package (for c2d, tfdata, filter)

pkg load signal;

STEP_LEN = 32;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', ...
                   'elliptic_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_ELLIPTIC_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_ELLIPTIC_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_elliptic_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace el_ref\n{\n\n');

% =============================================================================
% ncauer_direct: ncauer algorithm with nome computed directly from k1
% via the modular identity q = q1^(1/N), bypassing fminbnd.
% =============================================================================
function [zer, pol, T0] = ncauer_direct(Rp, Rs, n)
  ep  = sqrt(10^(Rp/10) - 1);
  es  = sqrt(10^(Rs/10) - 1);
  k1  = ep / es;
  k1p = sqrt(1 - k1^2);

  % Nome q1 from k1 via q-series approximation.
  sqrt_k1p = sqrt(k1p);
  q0_k1 = 0.5 * (1 - sqrt_k1p) / (1 + sqrt_k1p);
  q1 = q0_k1 + 2*q0_k1^5 + 15*q0_k1^9 + 150*q0_k1^13;

  % q = q1^(1/n) via modular identity (exact).
  q = exp(log(q1) / n);

  % Recover k from q via Jacobi theta functions.
  theta2 = 0;
  for nn = 0:100
    theta2 = theta2 + q^(nn*(nn+1));
  end
  theta2 = 2 * q^(1/4) * theta2;

  theta3 = 1;
  for nn = 1:100
    theta3 = theta3 + 2 * q^(nn^2);
  end

  k  = (theta2 / theta3)^2;
  ws = 1 / k;

  % ncauer theta-function algorithm (identical to Octave's ncauer from here).
  l = (1/(2*n)) * log((10^(0.05*Rp) + 1) / (10^(0.05*Rp) - 1));

  sig01 = 0;
  for m = 0:30
    sig01 = sig01 + (-1)^m * q^(m*(m+1)) * sinh((2*m+1)*l);
  end
  sig02 = 0;
  for m = 1:30
    sig02 = sig02 + (-1)^m * q^(m^2) * cosh(2*m*l);
  end
  sig0 = abs((2*q^(1/4)*sig01) / (1 + 2*sig02));

  w = sqrt((1 + k*sig0^2) * (1 + sig0^2/k));

  r = floor(n/2);
  wi = zeros(1, r);
  for ii = 1:r
    if rem(n, 2)
      mu = ii;
    else
      mu = ii - 1/2;
    end
    soma1 = 0;
    for m = 0:30
      soma1 = soma1 + 2*q^(1/4) * ((-1)^m * q^(m*(m+1)) * sin(((2*m+1)*pi*mu)/n));
    end
    soma2 = 0;
    for m = 1:30
      soma2 = soma2 + 2 * ((-1)^m * q^(m^2) * cos((2*m*pi*mu)/n));
    end
    wi(ii) = soma1 / (1 + soma2);
  end

  Vi  = sqrt((1 - k*(wi.^2)) .* (1 - (wi.^2)/k));
  A0i = 1 ./ (wi.^2);
  B0i = ((sig0*Vi).^2 + (w*wi).^2) ./ ((1 + sig0^2*wi.^2).^2);

  zer = [1i./wi, -1i./wi];
  pol = [(-sig0*Vi + 1i*wi.*w)./(1 + sig0^2*wi.^2), ...
         (-sig0*Vi - 1i*wi.*w)./(1 + sig0^2*wi.^2)];

  if rem(n, 2)
    pol = [pol, -sig0];
  end

  pol = sqrt(ws) * pol;
  zer = sqrt(ws) * zer;

  if rem(n, 2)
    T0 = sig0 * prod(B0i ./ A0i) * sqrt(ws);
  else
    T0 = 10^(-0.05*Rp) * prod(B0i ./ A0i);
  end
end

% =============================================================================
% Low-pass cases
% =============================================================================

lp_cases = {
    {2, 0.5, 40, 100,  1000},
    {4, 0.5, 40, 100,  1000},
    {3, 1.0, 60, 200,  4000},
};

for ci = 1:length(lp_cases)
    N   = lp_cases{ci}{1};
    Rp  = lp_cases{ci}{2};
    Rs  = lp_cases{ci}{3};
    fc  = lp_cases{ci}{4};
    fs  = lp_cases{ci}{5};
    wc  = 2 * pi * fc;

    % Normalized LP analog prototype via direct nome computation.
    [z_ap, p_ap, k_ap] = ncauer_direct(Rp, Rs, N);

    % Scale to passband edge wc.
    n_zeros   = length(z_ap);
    p_scaled  = p_ap  * wc;
    z_scaled  = z_ap  * wc;
    k_scaled  = k_ap  * wc^(N - n_zeros);
    [b_s, a_s] = zp2tf(z_scaled(:), p_scaled(:), k_scaled);
    sys_c = tf(b_s, a_s);

    u = ones(1, STEP_LEN);

    % ZOH digitization.
    sys_d      = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    % Zero-pad numerator to length N+1 to match Filter<T,N+1,N+1>.
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end

    y = filter(b_d, a_d, u);
    sname = sprintf('lp_%d_%.0frp_%.0frs_%dHz_%dHz', ...
                    N, Rp*10, Rs, fc, fs);

    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', N);
    fprintf(fid, '    static constexpr double ripple_db      = %.1f;\n', Rp);
    fprintf(fid, '    static constexpr double atten_db       = %.1f;\n', Rs);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
    for i = 1:length(b_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', b_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
    for i = 1:length(a_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', a_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
    for i = 1:STEP_LEN
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', y(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '};\n\n');
end

% =============================================================================
% High-pass cases
%
% LP-to-HP transform: a_hp[j] = a_lp[N-j]*wc^j, b_hp[j] = b_lp[N-j]*wc^j
% (coefficient reversal + wc scaling, same as our C++ HighPass path).
% =============================================================================

hp_cases = {
    {2, 0.5, 40, 100,  1000},
    {3, 1.0, 60, 200,  4000},
};

for ci = 1:length(hp_cases)
    N   = hp_cases{ci}{1};
    Rp  = hp_cases{ci}{2};
    Rs  = hp_cases{ci}{3};
    fc  = hp_cases{ci}{4};
    fs  = hp_cases{ci}{5};
    wc  = 2 * pi * fc;

    % Normalized LP prototype via direct nome computation.
    [z_ap, p_ap, k_ap] = ncauer_direct(Rp, Rs, N);
    [b_proto, a_proto]  = zp2tf(z_ap(:), p_ap(:), k_ap);

    % Pad b_proto to length N+1 (odd N has degree-N-1 numerator).
    while length(b_proto) < N + 1
        b_proto = [0, b_proto];
    end
    while length(a_proto) < N + 1
        a_proto = [0, a_proto];
    end

    % LP-to-HP: b_hp[j] = b_proto[N-j+1] * wc^j  (1-indexed).
    b_hp = zeros(1, N + 1);
    a_hp = zeros(1, N + 1);
    for j = 0:N
        sc        = wc^j;
        b_hp(j+1) = b_proto(N - j + 1) * sc;
        a_hp(j+1) = a_proto(N - j + 1) * sc;
    end

    sys_c = tf(b_hp, a_hp);
    u     = ones(1, STEP_LEN);

    % ZOH digitization.
    sys_d      = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end

    y = filter(b_d, a_d, u);
    sname = sprintf('hp_%d_%.0frp_%.0frs_%dHz_%dHz', ...
                    N, Rp*10, Rs, fc, fs);

    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', N);
    fprintf(fid, '    static constexpr double ripple_db      = %.1f;\n', Rp);
    fprintf(fid, '    static constexpr double atten_db       = %.1f;\n', Rs);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
    for i = 1:length(b_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', b_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
    for i = 1:length(a_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', a_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
    for i = 1:STEP_LEN
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', y(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '};\n\n');
end

fprintf(fid, '} // namespace el_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_ELLIPTIC_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
