% generate_elliptic_tests.m
%
% Generates elliptic_reference.hpp containing constexpr reference data
% for the constfilt Elliptic filter tests.
%
% Independent reference: uses the Signal package's stock ellip() entry
% point, which internally calls ncauer() and sftrans().  This script
% prepends octave/ to the function path so our local ncauer.m (a verbatim
% copy of upstream with a single-line fminbnd-tolerance patch) shadows the
% signal-package version.  Upstream's default fminbnd tolerance (~1e-4 on
% the elliptic-degree-equation solve) contaminates the analog pole
% locations at ~1e-6; our shadow forces TolX = 1e-15 so the reference is
% exact to machine precision.
%
% Run from the repo root:
%   octave --no-gui octave/generate_elliptic_tests.m
%
% Requires: Signal package (for ellip, c2d, tfdata, filter)

pkg load signal;

% Prepend octave/ so our shadowed ncauer.m wins over the signal package.
addpath(fileparts(mfilename('fullpath')), '-begin');

% Sanity check: confirm our ncauer is the one in use.
which_ncauer = which('ncauer');
if isempty(strfind(which_ncauer, fileparts(mfilename('fullpath'))))
    error('generate_elliptic_tests: shadowed ncauer.m not on path; got %s', ...
          which_ncauer);
end

STEP_LEN = 256;
CHIRP_LEN = 4096;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', ...
                   'elliptic_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_ELLIPTIC_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_ELLIPTIC_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_elliptic_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace el_ref\n{\n\n');

function emit_arr(fid, name, v)
    fprintf(fid, '    static constexpr double %s[%d] = {', name, length(v));
    for i = 1:length(v)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', v(i));
    end
    fprintf(fid, '};\n');
end

function emit_case(fid, kind, N, Rp, Rs, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c)
    sname = sprintf('%s_%d_%.0frp_%.0frs_%dHz_%dHz', ...
                    kind, N, Rp*10, Rs, fc, fs);
    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', N);
    fprintf(fid, '    static constexpr double ripple_db      = %.1f;\n', Rp);
    fprintf(fid, '    static constexpr double atten_db       = %.1f;\n', Rs);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    emit_arr(fid, 'b', b_d);
    emit_arr(fid, 'a', a_d);
    emit_arr(fid, 'step', y_step);
    emit_arr(fid, 'impulse', y_imp);
    emit_arr(fid, 'chirp_in', u_c);
    emit_arr(fid, 'chirp', y_c);
    fprintf(fid, '};\n\n');
end

function [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(Rp, Rs, N, wc, mode, fs, STEP_LEN, CHIRP_LEN, method)
    % mode   = 'low' or 'high' (analog filter type before discretization)
    % method = 'zoh' or 'matched' (discretization method)
    if strcmp(mode, 'high')
        [b_s, a_s] = ellip(N, Rp, Rs, wc, 'high', 's');
    else
        [b_s, a_s] = ellip(N, Rp, Rs, wc, 's');
    end
    sys_d      = c2d(tf(b_s, a_s), 1.0/fs, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    y_imp  = filter(b_d, a_d, [1, zeros(1, STEP_LEN-1)]);
    t_c    = (0:CHIRP_LEN-1) / fs;
    u_c    = chirp(t_c, 0, t_c(end), fs/2);
    y_c    = filter(b_d, a_d, u_c);
end

% =============================================================================
% Low-pass cases (ZOH and Matched-Z)
% =============================================================================
%
% Matched-Z reference data is generated even though constfilt's MatchedZ for
% elliptic is currently broken (issue #16: matched_z_discretize ignores finite
% zeros). The corresponding C++ tests are DISABLED-prefixed; they will activate
% automatically when #16 is fixed -- the reference values here are already
% correct (Octave's matched-Z maps zeros via z = exp(s*Ts) as it should).

lp_cases = {
    {2, 0.5, 40, 100,  1000},
    {4, 0.5, 40, 100,  1000},
    {5, 0.5, 40, 100,  1000},
    {6, 0.5, 40, 100,  1000},
    {7, 0.5, 40, 100,  1000},
    {8, 0.5, 40, 100,  1000},
    {3, 1.0, 60, 200,  4000},
};

for ci = 1:length(lp_cases)
    N   = lp_cases{ci}{1};
    Rp  = lp_cases{ci}{2};
    Rs  = lp_cases{ci}{3};
    fc  = lp_cases{ci}{4};
    fs  = lp_cases{ci}{5};
    wc  = 2 * pi * fc;

    [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(Rp, Rs, N, wc, 'low', fs, STEP_LEN, CHIRP_LEN, 'zoh');
    emit_case(fid, 'lp', N, Rp, Rs, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

    [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(Rp, Rs, N, wc, 'low', fs, STEP_LEN, CHIRP_LEN, 'matched');
    emit_case(fid, 'lp_mz', N, Rp, Rs, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);
end

% =============================================================================
% High-pass cases (ZOH and Matched-Z)
% =============================================================================

hp_cases = {
    {2, 0.5, 40, 100,  1000},
    {4, 0.5, 40, 100,  1000},
    {5, 0.5, 40, 100,  1000},
    {6, 0.5, 40, 100,  1000},
    {7, 0.5, 40, 100,  1000},
    {8, 0.5, 40, 100,  1000},
    {3, 1.0, 60, 200,  4000},
};

for ci = 1:length(hp_cases)
    N   = hp_cases{ci}{1};
    Rp  = hp_cases{ci}{2};
    Rs  = hp_cases{ci}{3};
    fc  = hp_cases{ci}{4};
    fs  = hp_cases{ci}{5};
    wc  = 2 * pi * fc;

    [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(Rp, Rs, N, wc, 'high', fs, STEP_LEN, CHIRP_LEN, 'zoh');
    emit_case(fid, 'hp', N, Rp, Rs, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

    [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(Rp, Rs, N, wc, 'high', fs, STEP_LEN, CHIRP_LEN, 'matched');
    emit_case(fid, 'hp_mz', N, Rp, Rs, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);
end

fprintf(fid, '} // namespace el_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_ELLIPTIC_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
