% generate_continuous_tf_tests.m
%
% Generates continuous_tf_reference.hpp containing constexpr reference data
% for the constfilt ContinuousTF filter tests.
%
% Run from the octave/ directory:
%   octave --no-gui generate_continuous_tf_tests.m
%
% Requires: Signal package (for c2d, ss, tf, tfdata, filter)

pkg load signal;

STEP_LEN = 32;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', 'continuous_tf_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_continuous_tf_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace ctf_ref\n{\n\n');

% ---------------------------------------------------------------------------
% Case 1: H(s) = 1/(s+1), ZOH, fs=10 Hz  (N=1, strictly proper)
%   Continuous SS: A=[-1], B=[1], C=[1], D=0
%   ZOH: Ad=exp(-0.1), Bd=1-exp(-0.1)
% ---------------------------------------------------------------------------
b_s = [0, 1];
a_s = [1, 1];
fs  = 10.0;
Ts  = 1.0 / fs;
sys_c = tf(b_s, a_s);
sys_d = c2d(sys_c, Ts, 'zoh');
[b_d, a_d] = tfdata(sys_d, 'v');
while length(b_d) < length(a_d); b_d = [0, b_d]; end
u = ones(1, STEP_LEN);
y = filter(b_d, a_d, u);

sname = 'case_1_zoh_fs10';
fprintf(fid, 'struct %s\n{\n', sname);
fprintf(fid, '    // H(s) = 1/(s+1), ZOH, fs=10 Hz\n');
fprintf(fid, '    static constexpr double b_s[2] = {%.17g, %.17g};\n', b_s(1), b_s(2));
fprintf(fid, '    static constexpr double a_s[2] = {%.17g, %.17g};\n', a_s(1), a_s(2));
fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
for i = 1:length(b_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', b_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
for i = 1:length(a_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', a_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
for i = 1:STEP_LEN
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', y(i));
end
fprintf(fid, '};\n');
fprintf(fid, '};\n\n');

% ---------------------------------------------------------------------------
% Case 2: H(s) = 1/(s^2 + 3s + 2), ZOH, fs=10 Hz  (N=2, strictly proper)
%   Poles at s=-1 and s=-2 (stable)
% ---------------------------------------------------------------------------
b_s = [0, 0, 1];
a_s = [1, 3, 2];
fs  = 10.0;
Ts  = 1.0 / fs;
sys_c = tf(b_s, a_s);
sys_d = c2d(sys_c, Ts, 'zoh');
[b_d, a_d] = tfdata(sys_d, 'v');
while length(b_d) < length(a_d); b_d = [0, b_d]; end
y = filter(b_d, a_d, u);

sname = 'case_2_zoh_fs10';
fprintf(fid, 'struct %s\n{\n', sname);
fprintf(fid, '    // H(s) = 1/(s^2+3s+2), ZOH, fs=10 Hz\n');
fprintf(fid, '    static constexpr double b_s[3] = {%.17g, %.17g, %.17g};\n', b_s(1), b_s(2), b_s(3));
fprintf(fid, '    static constexpr double a_s[3] = {%.17g, %.17g, %.17g};\n', a_s(1), a_s(2), a_s(3));
fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
for i = 1:length(b_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', b_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
for i = 1:length(a_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', a_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
for i = 1:STEP_LEN
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', y(i));
end
fprintf(fid, '};\n');
fprintf(fid, '};\n\n');

% ---------------------------------------------------------------------------
% Case 3: H(s) = (s+2)/(s+1), ZOH, fs=10 Hz  (N=1, proper with D!=0)
%   Poles at s=-1, DC gain = 2
% ---------------------------------------------------------------------------
b_s = [1, 2];
a_s = [1, 1];
fs  = 10.0;
Ts  = 1.0 / fs;
sys_c = tf(b_s, a_s);
sys_d = c2d(sys_c, Ts, 'zoh');
[b_d, a_d] = tfdata(sys_d, 'v');
while length(b_d) < length(a_d); b_d = [0, b_d]; end
y = filter(b_d, a_d, u);

sname = 'case_3_proper_zoh_fs10';
fprintf(fid, 'struct %s\n{\n', sname);
fprintf(fid, '    // H(s) = (s+2)/(s+1), ZOH, fs=10 Hz\n');
fprintf(fid, '    static constexpr double b_s[2] = {%.17g, %.17g};\n', b_s(1), b_s(2));
fprintf(fid, '    static constexpr double a_s[2] = {%.17g, %.17g};\n', a_s(1), a_s(2));
fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
for i = 1:length(b_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', b_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
for i = 1:length(a_d)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', a_d(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
for i = 1:STEP_LEN
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', y(i));
end
fprintf(fid, '};\n');
fprintf(fid, '};\n\n');

% ---------------------------------------------------------------------------
% Case 4: H(s) = 1/(s^2 + 3s + 2), MatchedZ, fs=10 Hz
% ---------------------------------------------------------------------------
b_s = [0, 0, 1];
a_s = [1, 3, 2];
fs  = 10.0;
Ts  = 1.0 / fs;
sys_c = tf(b_s, a_s);
sys_mz = c2d(sys_c, Ts, 'matched');
[b_mz, a_mz] = tfdata(sys_mz, 'v');
while length(b_mz) < length(a_mz); b_mz = [0, b_mz]; end
y = filter(b_mz, a_mz, u);

sname = 'case_4_mz_fs10';
fprintf(fid, 'struct %s\n{\n', sname);
fprintf(fid, '    // H(s) = 1/(s^2+3s+2), MatchedZ, fs=10 Hz\n');
fprintf(fid, '    static constexpr double b_s[3] = {%.17g, %.17g, %.17g};\n', b_s(1), b_s(2), b_s(3));
fprintf(fid, '    static constexpr double a_s[3] = {%.17g, %.17g, %.17g};\n', a_s(1), a_s(2), a_s(3));
fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
fprintf(fid, '    static constexpr double b[%d] = {', length(b_mz));
for i = 1:length(b_mz)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', b_mz(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double a[%d] = {', length(a_mz));
for i = 1:length(a_mz)
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', a_mz(i));
end
fprintf(fid, '};\n');
fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
for i = 1:STEP_LEN
    if i > 1; fprintf(fid, ', '); end
    fprintf(fid, '%.17g', y(i));
end
fprintf(fid, '};\n');
fprintf(fid, '};\n\n');

fprintf(fid, '} // namespace ctf_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
