% generate_butterworth_tests.m
%
% Generates butterworth_reference.hpp containing constexpr reference data
% for the constfilt Butterworth filter tests.
%
% Run from the octave/ directory:
%   octave --no-gui generate_butterworth_tests.m
%
% Requires: Signal package (for buttap, zp2tf, c2d, tfdata, filter, lp2hp)

pkg load signal;

STEP_LEN = 256;
CHIRP_LEN = 4096;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', 'butterworth_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_butterworth_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace bw_ref\n{\n\n');

% ---- helpers ----------------------------------------------------------------

function emit_arr(fid, name, v)
    fprintf(fid, '    static constexpr double %s[%d] = {', name, length(v));
    for i = 1:length(v)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', v(i));
    end
    fprintf(fid, '};\n');
end

function emit_case(fid, sname, ord, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c)
    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', ord);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    emit_arr(fid, 'b', b_d);
    emit_arr(fid, 'a', a_d);
    emit_arr(fid, 'step', y_step);
    emit_arr(fid, 'impulse', y_imp);
    emit_arr(fid, 'chirp_in', u_c);
    emit_arr(fid, 'chirp', y_c);
    fprintf(fid, '};\n\n');
end

% =============================================================================
% Low-pass cases
% =============================================================================

lpf_cases = {
    {1, 100,  1000},
    {2, 100,  1000},
    {4, 100,  1000},
    {5, 100,  1000},
    {6, 100,  1000},
    {7, 100,  1000},
    {8, 100,  1000},
    {2, 500,  8000},
    {3, 200,  4000},
};

for ci = 1:length(lpf_cases)
    ord = lpf_cases{ci}{1};
    fc  = lpf_cases{ci}{2};
    fs  = lpf_cases{ci}{3};
    wc  = 2 * pi * fc;

    % Build normalized analog prototype and denormalize to wc
    [z_p, p_p, k_p] = buttap(ord);
    p_scaled = p_p * wc;
    k_scaled = k_p * wc^ord;
    [b_s, a_s] = zp2tf(z_p, p_scaled, k_scaled);
    sys_c = tf(b_s, a_s);
    u = ones(1, STEP_LEN);

    % --- ZOH ---
    sys_d = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    % ZOH of an all-pole system gives numerator of degree N-1.
    % Zero-pad b_d to length N+1 so it matches constfilt's Filter<T,N+1,N+1>.
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end

    y_step = filter(b_d, a_d, u);
    y_imp  = filter(b_d, a_d, [1, zeros(1, STEP_LEN-1)]);
    t_c    = (0:CHIRP_LEN-1) / fs;
    u_c    = chirp(t_c, 0, t_c(end), fs/2);
    y_c    = filter(b_d, a_d, u_c);
    emit_case(fid, sprintf('case_%d_%dHz_%dHz', ord, fc, fs), ...
              ord, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

    % --- Matched-Z ---
    sys_mz = c2d(sys_c, 1.0/fs, 'matched');
    [b_mz, a_mz] = tfdata(sys_mz, 'v');

    while length(b_mz) < length(a_mz)
        b_mz = [0, b_mz];
    end

    y_step_mz = filter(b_mz, a_mz, u);
    y_imp_mz  = filter(b_mz, a_mz, [1, zeros(1, STEP_LEN-1)]);
    y_c_mz    = filter(b_mz, a_mz, u_c);
    emit_case(fid, sprintf('case_mz_%d_%dHz_%dHz', ord, fc, fs), ...
              ord, fc, fs, b_mz, a_mz, y_step_mz, y_imp_mz, u_c, y_c_mz);
end

% =============================================================================
% High-pass cases (ZOH + Matched-Z)
% =============================================================================
%
% HP Butterworth has N zeros at s=0 which map to z=1 under matched-Z, but
% the constfilt implementation hardcodes zeros at z=-1 (issue #16).  The
% matched-Z reference data below is correct (Octave maps all zeros properly);
% the corresponding C++ tests are disabled until issue #16 is fixed.

hpf_cases = {
    {1, 100,  1000},
    {2, 100,  1000},
    {4, 100,  1000},
    {5, 100,  1000},
    {6, 100,  1000},
    {7, 100,  1000},
    {8, 100,  1000},
    {2, 500,  8000},
    {3, 200,  4000},
};

for ci = 1:length(hpf_cases)
    ord = hpf_cases{ci}{1};
    fc  = hpf_cases{ci}{2};
    fs  = hpf_cases{ci}{3};
    wc  = 2 * pi * fc;

    % LP prototype → LP-to-HP transformation: poles map as wc/p, N zeros at
    % s=0, unity high-frequency gain.
    [z_p, p_p, k_p] = buttap(ord);
    p_hp = wc ./ p_p;
    z_hp = zeros(ord, 1);
    [b_s, a_s] = zp2tf(z_hp, p_hp, 1);
    sys_c = tf(b_s, a_s);
    u = ones(1, STEP_LEN);

    % --- ZOH ---
    sys_d = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    % HPF is proper (not strictly proper), no zero-padding needed.
    y_step = filter(b_d, a_d, u);
    y_imp  = filter(b_d, a_d, [1, zeros(1, STEP_LEN-1)]);
    t_c    = (0:CHIRP_LEN-1) / fs;
    u_c    = chirp(t_c, 0, t_c(end), fs/2);
    y_c    = filter(b_d, a_d, u_c);
    emit_case(fid, sprintf('case_hp_%d_%dHz_%dHz', ord, fc, fs), ...
              ord, fc, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

    % --- Matched-Z ---
    sys_mz = c2d(sys_c, 1.0/fs, 'matched');
    [b_mz, a_mz] = tfdata(sys_mz, 'v');

    y_step_mz = filter(b_mz, a_mz, u);
    y_imp_mz  = filter(b_mz, a_mz, [1, zeros(1, STEP_LEN-1)]);
    y_c_mz    = filter(b_mz, a_mz, u_c);
    emit_case(fid, sprintf('case_mz_hp_%d_%dHz_%dHz', ord, fc, fs), ...
              ord, fc, fs, b_mz, a_mz, y_step_mz, y_imp_mz, u_c, y_c_mz);
end

fprintf(fid, '} // namespace bw_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
