% generate_continuous_tf_tests.m
%
% Generates continuous_tf_reference.hpp containing constexpr reference data
% for the constfilt ContinuousTF filter tests.
%
% Run from the octave/ directory:
%   octave --no-gui generate_continuous_tf_tests.m
%
% Requires: Signal package (for c2d, ss, tf, tfdata, filter, chirp)

pkg load signal;

STEP_LEN  = 256;
CHIRP_LEN = 4096;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', 'continuous_tf_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_continuous_tf_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace ctf_ref\n{\n\n');

function emit_arr(fid, name, v)
    fprintf(fid, '    static constexpr double %s[%d] = {', name, length(v));
    for i = 1:length(v)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', v(i));
    end
    fprintf(fid, '};\n');
end

function [b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(b_s, a_s, fs, method, STEP_LEN, CHIRP_LEN)
    Ts    = 1.0 / fs;
    sys_c = tf(b_s, a_s);
    sys_d = c2d(sys_c, Ts, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    y_imp  = filter(b_d, a_d, [1, zeros(1, STEP_LEN-1)]);
    t_c    = (0:CHIRP_LEN-1) / fs;
    u_c    = chirp(t_c, 0, t_c(end), fs/2);
    y_c    = filter(b_d, a_d, u_c);
end

function emit_case(fid, sname, comment, b_s, a_s, fs, b_d, a_d, y_step, y_imp, u_c, y_c)
    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    // %s\n', comment);
    emit_arr(fid, 'b_s', b_s);
    emit_arr(fid, 'a_s', a_s);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    emit_arr(fid, 'b', b_d);
    emit_arr(fid, 'a', a_d);
    emit_arr(fid, 'step',     y_step);
    emit_arr(fid, 'impulse',  y_imp);
    emit_arr(fid, 'chirp_in', u_c);
    emit_arr(fid, 'chirp',    y_c);
    fprintf(fid, '};\n\n');
end

% ---------------------------------------------------------------------------
% Case 1: H(s) = 1/(s+1), ZOH, fs=10 Hz  (N=1, strictly proper)
% ---------------------------------------------------------------------------
b_s = [0, 1];
a_s = [1, 1];
fs  = 10.0;
[b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(b_s, a_s, fs, 'zoh', STEP_LEN, CHIRP_LEN);
emit_case(fid, 'case_1_zoh_fs10', 'H(s) = 1/(s+1), ZOH, fs=10 Hz', ...
          b_s, a_s, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

% ---------------------------------------------------------------------------
% Case 2: H(s) = 1/(s^2 + 3s + 2), ZOH, fs=10 Hz  (N=2, strictly proper)
%   Poles at s=-1 and s=-2 (stable)
% ---------------------------------------------------------------------------
b_s = [0, 0, 1];
a_s = [1, 3, 2];
fs  = 10.0;
[b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(b_s, a_s, fs, 'zoh', STEP_LEN, CHIRP_LEN);
emit_case(fid, 'case_2_zoh_fs10', 'H(s) = 1/(s^2+3s+2), ZOH, fs=10 Hz', ...
          b_s, a_s, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

% ---------------------------------------------------------------------------
% Case 3: H(s) = (s+2)/(s+1), ZOH, fs=10 Hz  (N=1, proper with D!=0)
%   Poles at s=-1, DC gain = 2
% ---------------------------------------------------------------------------
b_s = [1, 2];
a_s = [1, 1];
fs  = 10.0;
[b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(b_s, a_s, fs, 'zoh', STEP_LEN, CHIRP_LEN);
emit_case(fid, 'case_3_proper_zoh_fs10', 'H(s) = (s+2)/(s+1), ZOH, fs=10 Hz', ...
          b_s, a_s, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

% ---------------------------------------------------------------------------
% Case 4: H(s) = 1/(s^2 + 3s + 2), MatchedZ, fs=10 Hz
% ---------------------------------------------------------------------------
b_s = [0, 0, 1];
a_s = [1, 3, 2];
fs  = 10.0;
[b_d, a_d, y_step, y_imp, u_c, y_c] = design_and_filter(b_s, a_s, fs, 'matched', STEP_LEN, CHIRP_LEN);
emit_case(fid, 'case_4_mz_fs10', 'H(s) = 1/(s^2+3s+2), MatchedZ, fs=10 Hz', ...
          b_s, a_s, fs, b_d, a_d, y_step, y_imp, u_c, y_c);

fprintf(fid, '} // namespace ctf_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_CONTINUOUS_TF_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
