% generate_butterworth_tests.m
%
% Generates butterworth_reference.hpp containing constexpr reference data
% for the constfilt Butterworth filter tests.
%
% Run from the octave/ directory:
%   octave --no-gui generate_butterworth_tests.m
%
% Requires: Signal package (for buttap, zp2tf, c2d, tfdata, filter, lp2hp)

pkg load signal;

STEP_LEN = 32;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'tests', 'butterworth_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by octave/generate_butterworth_tests.m\n');
fprintf(fid, '// Do not edit manually.\n\n');
fprintf(fid, 'namespace bw_ref\n{\n\n');

% =============================================================================
% Low-pass cases
% =============================================================================

lpf_cases = {
    {2, 100,  1000},
    {4, 100,  1000},
    {2, 500,  8000},
    {3, 200,  4000},
};

for ci = 1:length(lpf_cases)
    ord = lpf_cases{ci}{1};
    fc  = lpf_cases{ci}{2};
    fs  = lpf_cases{ci}{3};
    wc  = 2 * pi * fc;

    % Build normalized analog prototype and denormalize to wc
    [z_p, p_p, k_p] = buttap(ord);
    p_scaled = p_p * wc;
    k_scaled = k_p * wc^ord;
    [b_s, a_s] = zp2tf(z_p, p_scaled, k_scaled);
    sys_c = tf(b_s, a_s);
    u = ones(1, STEP_LEN);

    % --- ZOH ---
    sys_d = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    % ZOH of an all-pole system gives numerator of degree N-1.
    % Zero-pad b_d to length N+1 so it matches constfilt's Filter<T,N+1,N+1>.
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end

    y_zoh = filter(b_d, a_d, u);
    sname = sprintf('case_%d_%dHz_%dHz', ord, fc, fs);

    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', ord);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
    for i = 1:length(b_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', b_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
    for i = 1:length(a_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', a_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
    for i = 1:STEP_LEN
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', y_zoh(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '};\n\n');

    % --- Matched-Z ---
    sys_mz = c2d(sys_c, 1.0/fs, 'matched');
    [b_mz, a_mz] = tfdata(sys_mz, 'v');

    % Zero-pad b_mz to match length of a_mz if needed.
    while length(b_mz) < length(a_mz)
        b_mz = [0, b_mz];
    end

    y_mz = filter(b_mz, a_mz, u);
    sname_mz = sprintf('case_mz_%d_%dHz_%dHz', ord, fc, fs);

    fprintf(fid, 'struct %s\n{\n', sname_mz);
    fprintf(fid, '    static constexpr int    order          = %d;\n', ord);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    fprintf(fid, '    static constexpr double b[%d] = {', length(b_mz));
    for i = 1:length(b_mz)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', b_mz(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double a[%d] = {', length(a_mz));
    for i = 1:length(a_mz)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', a_mz(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
    for i = 1:STEP_LEN
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', y_mz(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '};\n\n');
end

% =============================================================================
% High-pass cases (ZOH only — matched-Z assumes all-pole and does not apply)
% =============================================================================

hpf_cases = {
    {2, 100,  1000},
    {4, 100,  1000},
    {2, 500,  8000},
    {3, 200,  4000},
};

for ci = 1:length(hpf_cases)
    ord = hpf_cases{ci}{1};
    fc  = hpf_cases{ci}{2};
    fs  = hpf_cases{ci}{3};
    wc  = 2 * pi * fc;

    % LP prototype → LP-to-HP transformation: poles map as wc/p, N zeros at
    % s=0, unity high-frequency gain.
    [z_p, p_p, k_p] = buttap(ord);
    p_hp = wc ./ p_p;
    z_hp = zeros(ord, 1);
    [b_s, a_s] = zp2tf(z_hp, p_hp, 1);
    sys_c = tf(b_s, a_s);
    u = ones(1, STEP_LEN);

    % --- ZOH ---
    sys_d = c2d(sys_c, 1.0/fs, 'zoh');
    [b_d, a_d] = tfdata(sys_d, 'v');

    % HPF is proper (not strictly proper), no zero-padding needed.
    y_zoh = filter(b_d, a_d, u);
    sname = sprintf('case_hp_%d_%dHz_%dHz', ord, fc, fs);

    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int    order          = %d;\n', ord);
    fprintf(fid, '    static constexpr double cutoff_hz      = %.1f;\n', fc);
    fprintf(fid, '    static constexpr double sample_rate_hz = %.1f;\n\n', fs);
    fprintf(fid, '    static constexpr double b[%d] = {', length(b_d));
    for i = 1:length(b_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', b_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double a[%d] = {', length(a_d));
    for i = 1:length(a_d)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', a_d(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '    static constexpr double step[%d] = {', STEP_LEN);
    for i = 1:STEP_LEN
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', y_zoh(i));
    end
    fprintf(fid, '};\n');
    fprintf(fid, '};\n\n');
end

fprintf(fid, '} // namespace bw_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_BUTTERWORTH_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
