% generate_accuracy_reference.m
%
% Generates profiling/accuracy_reference.hpp: Octave-computed b/a coefficients
% and 256-sample step responses for Butterworth and Elliptic filters at orders
% up to 25, for all three discretization methods (ZOH, MatchedZ, Tustin).
%
% The generated header is consumed by profiling/bench_accuracy.cpp to compare
% constfilt output against this independent Octave reference.  Differences
% reveal numerical accuracy breakdowns at high orders or for specific methods.
%
% Run from the repo root:
%   octave --no-gui profiling/octave/generate_accuracy_reference.m
%
% Requires: Signal package, Control package
%
% step_sos is computed via ZPK form throughout to avoid the precision loss of
% the polynomial tf2sos path at high N.  Two different ZPK paths are used:
%
%   Tustin / prewarped Tustin:
%     signal-package bilinear(z, p, k, T) maps each pole directly,
%     avoiding the gain-underflow that afflicts the control-package c2d(zpk)
%     for N >= 23.
%
%   ZOH / MatchedZ:
%     control-package c2d(zpk(...), Ts, method) followed by zpkdata, which
%     uses eigenvalue-based algorithms internally (more stable than polynomial
%     tf2sos).  ZOH gain underflows at very high N (>= 23) but ZOH + SOS is
%     static_assert'd away in constfilt, so step_sos for ZOH is only used for
%     the _vs_sos_ref comparison rows (already broken for N >> 12).

pkg load signal;

% Shadow the signal package's ncauer.m with our fixed-tolerance version so
% elliptic reference values are exact to machine precision (same as the main
% test suite).
addpath(fullfile(fileparts(mfilename('fullpath')), '..', '..', 'octave'), '-begin');
which_ncauer = which('ncauer');
expected_dir  = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'octave');
if isempty(strfind(which_ncauer, 'ncauer.m')) || ...
   isempty(strfind(canonicalize_file_name(which_ncauer), ...
                   canonicalize_file_name(expected_dir)))
    error('generate_accuracy_reference: shadowed ncauer.m not on path; got %s', ...
          which_ncauer);
end

STEP_LEN = 256;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'accuracy_reference.hpp');
fid = fopen(outfile, 'w');
if fid < 0
    error('generate_accuracy_reference: failed to open output file: %s', outfile);
end

fprintf(fid, '#ifndef CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by profiling/octave/generate_accuracy_reference.m\n');
fprintf(fid, '// Do not edit manually.\n');
fprintf(fid, '// Octave-computed reference for accuracy comparison against constfilt.\n');
fprintf(fid, '// Filter spec: fc=100 Hz, fs=1000 Hz; elliptic: Rp=0.5 dB, Rs=40 dB.\n\n');
fprintf(fid, 'namespace acc_ref\n{\n\n');

% helpers

function emit_arr(fid, name, v)
    fprintf(fid, '    static constexpr double %s[%d] = {', name, length(v));
    for i = 1:length(v)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', v(i));
    end
    fprintf(fid, '};\n');
end

% Compute step_sos from digital ZPK via zp2sos + sosfilt.
function y_sos = step_sos_zpk(z_d, p_d, k_d, STEP_LEN)
    sos = zp2sos(z_d, p_d, k_d);
    y_sos = sosfilt(sos, ones(1, STEP_LEN));
end

% Discretize analog ZPK to digital ZPK for Tustin methods.
% Uses signal-package bilinear(z, p, k, T) which maps poles individually
% and avoids the gain underflow that affects the control-package c2d(zpk)
% path for N >= 23.  T = 1/fs (sampling period).
% For prewarped Tustin, the caller pre-scales the prototype by wc_pw before
% calling this function, then passes standard bilinear (no warp arg needed).
function [z_d, p_d, k_d] = analog_to_digital_zpk_tustin(z_a, p_a, k_a, fs)
    [z_d, p_d, k_d] = bilinear(z_a, p_a, k_a, 1/fs);
end

% Discretize analog ZPK to digital ZPK for ZOH and MatchedZ methods.
% Uses control-package c2d(zpk(...), Ts, method) + zpkdata, which uses
% eigenvalue-based algorithms more stable than polynomial tf2sos.
function [z_d, p_d, k_d] = analog_to_digital_zpk(z_a, p_a, k_a, fs, method)
    sys_d = c2d(zpk(z_a, p_a, k_a), 1/fs, method);
    [z_d, p_d, k_d] = zpkdata(sys_d, 'v');
end

function emit_struct(fid, sname, ord, b_d, a_d, y_step, y_sos)
    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int order = %d;\n', ord);
    emit_arr(fid, 'b', b_d);
    emit_arr(fid, 'a', a_d);
    emit_arr(fid, 'step', y_step);
    emit_arr(fid, 'step_sos', y_sos);
    fprintf(fid, '};\n\n');
end

% Design a continuous-time Butterworth LP, discretize, zero-pad b if needed,
% and compute the step response.  Returns both TF form (for the direct-form
% reference) and ZPK form (for the SOS reference via step_sos_zpk).
function [b_d, a_d, y_step, z_d, p_d, k_d] = bw_design(ord, fc, fs, method)
    wc = 2 * pi * fc;
    [z_a, p_a, k_a] = buttap(ord);
    p_a = p_a * wc;
    k_a = k_a * wc^ord;
    % Direct-form path (for b_d, a_d, y_step reference)
    [b_s, a_s] = zp2tf(z_a, p_a, k_a);
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    % ZPK path (for step_sos reference)
    if strcmp(method, 'tustin')
        [z_d, p_d, k_d] = analog_to_digital_zpk_tustin(z_a, p_a, k_a, fs);
    else
        [z_d, p_d, k_d] = analog_to_digital_zpk(z_a, p_a, k_a, fs, method);
    end
end

% Pre-warped bilinear: design the analog prototype at the pre-warped frequency
%   wc_pw = 2*fs*tan(pi*fc/fs)
% then apply the standard bilinear (c2d 'tustin').  This ensures the standard
% bilinear maps wc_pw to exactly fc Hz digital, so the -3dB point lands at
% the specified cutoff.  Octave's c2d ignores the 4th-argument warp frequency,
% so we implement the pre-warp manually.
function [b_d, a_d, y_step, z_d, p_d, k_d] = bw_design_pw(ord, fc, fs)
    wc_pw = 2 * fs * tan(pi * fc / fs);
    [z_a, p_a, k_a] = buttap(ord);
    p_a = p_a * wc_pw;
    k_a = k_a * wc_pw^ord;
    % Direct-form path
    [b_s, a_s] = zp2tf(z_a, p_a, k_a);
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, 'tustin');
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    % ZPK path: pre-scaled prototype, standard bilinear via signal package
    [z_d, p_d, k_d] = analog_to_digital_zpk_tustin(z_a, p_a, k_a, fs);
end

% Design a continuous-time Elliptic LP, discretize, zero-pad, step response.
function [b_d, a_d, y_step, z_d, p_d, k_d] = el_design(ord, Rp, Rs, fc, fs, method)
    wc = 2 * pi * fc;
    % Direct-form path
    [b_s, a_s] = ellip(ord, Rp, Rs, wc, 's');
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    % ZPK path
    [z_s, p_s, k_s] = ellip(ord, Rp, Rs, wc, 's');
    if strcmp(method, 'tustin')
        [z_d, p_d, k_d] = analog_to_digital_zpk_tustin(z_s, p_s, k_s, fs);
    else
        [z_d, p_d, k_d] = analog_to_digital_zpk(z_s, p_s, k_s, fs, method);
    end
end

function [b_d, a_d, y_step, z_d, p_d, k_d] = el_design_pw(ord, Rp, Rs, fc, fs)
    wc_pw = 2 * fs * tan(pi * fc / fs);
    % Direct-form path
    [b_s, a_s] = ellip(ord, Rp, Rs, wc_pw, 's');
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, 'tustin');
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
    % ZPK path
    [z_s, p_s, k_s] = ellip(ord, Rp, Rs, wc_pw, 's');
    [z_d, p_d, k_d] = analog_to_digital_zpk_tustin(z_s, p_s, k_s, fs);
end

% Butterworth LP, orders 1-25, all three methods + pre-warped Tustin

fprintf(fid, '// Butterworth lowpass: fc=100 Hz, fs=1000 Hz\n\n');

fc = 100;
fs = 1000;

for ord = 1:25
    for mi = 1:4
        methods = {'zoh', 'matched', 'tustin', 'prewarp'};
        method  = methods{mi};
        labels  = {'zoh', 'matchedz', 'tustin', 'prewarp'};
        label   = labels{mi};

        if strcmp(method, 'prewarp')
            [b_d, a_d, y_step, z_d, p_d, k_d] = bw_design_pw(ord, fc, fs);
        else
            [b_d, a_d, y_step, z_d, p_d, k_d] = bw_design(ord, fc, fs, method);
        end
        y_sos = step_sos_zpk(z_d, p_d, k_d, STEP_LEN);
        sname = sprintf('bw_%s_N%d', label, ord);
        emit_struct(fid, sname, ord, b_d, a_d, y_step, y_sos);
    end
end

% Elliptic LP, orders 2-25, all three methods + pre-warped Tustin

fprintf(fid, '// Elliptic lowpass: fc=100 Hz, fs=1000 Hz, Rp=0.5 dB, Rs=40 dB\n\n');

Rp = 0.5;
Rs = 40;

for ord = 2:25
    for mi = 1:4
        methods = {'zoh', 'matched', 'tustin', 'prewarp'};
        method  = methods{mi};
        labels  = {'zoh', 'matchedz', 'tustin', 'prewarp'};
        label   = labels{mi};

        if strcmp(method, 'prewarp')
            [b_d, a_d, y_step, z_d, p_d, k_d] = el_design_pw(ord, Rp, Rs, fc, fs);
        else
            [b_d, a_d, y_step, z_d, p_d, k_d] = el_design(ord, Rp, Rs, fc, fs, method);
        end
        y_sos = step_sos_zpk(z_d, p_d, k_d, STEP_LEN);
        sname = sprintf('el_%s_N%d', label, ord);
        emit_struct(fid, sname, ord, b_d, a_d, y_step, y_sos);
    end
end

fprintf(fid, '} // namespace acc_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
