% generate_accuracy_reference.m
%
% Generates profiling/accuracy_reference.hpp: Octave-computed b/a coefficients
% and 256-sample step responses for Butterworth and Elliptic filters at orders
% up to 12, for all three discretization methods (ZOH, MatchedZ, Tustin).
%
% The generated header is consumed by profiling/bench_accuracy.cpp to compare
% constfilt output against this independent Octave reference.  Differences
% reveal numerical accuracy breakdowns at high orders or for specific methods.
%
% Run from the repo root:
%   octave --no-gui profiling/octave/generate_accuracy_reference.m
%
% Requires: Signal package

pkg load signal;

% Shadow the signal package's ncauer.m with our fixed-tolerance version so
% elliptic reference values are exact to machine precision (same as the main
% test suite).
addpath(fullfile(fileparts(mfilename('fullpath')), '..', '..', 'octave'), '-begin');
which_ncauer = which('ncauer');
if isempty(strfind(which_ncauer, 'octave'))
    error('generate_accuracy_reference: shadowed ncauer.m not on path; got %s', ...
          which_ncauer);
end

STEP_LEN = 256;

outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'accuracy_reference.hpp');
fid = fopen(outfile, 'w');

fprintf(fid, '#ifndef CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n');
fprintf(fid, '#define CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n\n');
fprintf(fid, '// AUTO-GENERATED by profiling/octave/generate_accuracy_reference.m\n');
fprintf(fid, '// Do not edit manually.\n');
fprintf(fid, '// Octave-computed reference for accuracy comparison against constfilt.\n');
fprintf(fid, '// Filter spec: fc=100 Hz, fs=1000 Hz; elliptic: Rp=0.5 dB, Rs=40 dB.\n\n');
fprintf(fid, 'namespace acc_ref\n{\n\n');

% ── helpers ──────────────────────────────────────────────────────────────────

function emit_arr(fid, name, v)
    fprintf(fid, '    static constexpr double %s[%d] = {', name, length(v));
    for i = 1:length(v)
        if i > 1; fprintf(fid, ', '); end
        fprintf(fid, '%.17g', v(i));
    end
    fprintf(fid, '};\n');
end

function emit_struct(fid, sname, ord, b_d, a_d, y_step)
    fprintf(fid, 'struct %s\n{\n', sname);
    fprintf(fid, '    static constexpr int order = %d;\n', ord);
    emit_arr(fid, 'b', b_d);
    emit_arr(fid, 'a', a_d);
    emit_arr(fid, 'step', y_step);
    fprintf(fid, '};\n\n');
end

% Design a continuous-time Butterworth LP, discretize, zero-pad b if needed,
% and compute the step response.
function [b_d, a_d, y_step] = bw_design(ord, fc, fs, method)
    wc = 2 * pi * fc;
    [z_p, p_p, k_p] = buttap(ord);
    p_scaled = p_p * wc;
    k_scaled = k_p * wc^ord;
    [b_s, a_s] = zp2tf(z_p, p_scaled, k_scaled);
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
end

% Design a continuous-time Elliptic LP, discretize, zero-pad, step response.
function [b_d, a_d, y_step] = el_design(ord, Rp, Rs, fc, fs, method)
    wc = 2 * pi * fc;
    [b_s, a_s] = ellip(ord, Rp, Rs, wc, 's');
    sys_d = c2d(tf(b_s, a_s), 1.0/fs, method);
    [b_d, a_d] = tfdata(sys_d, 'v');
    while length(b_d) < length(a_d)
        b_d = [0, b_d];
    end
    STEP_LEN = 256;
    y_step = filter(b_d, a_d, ones(1, STEP_LEN));
end

% ── Butterworth LP, orders 1–12, all three methods ───────────────────────────

fprintf(fid, '// Butterworth lowpass: fc=100 Hz, fs=1000 Hz\n\n');

fc = 100;
fs = 1000;

for ord = 1:12
    for mi = 1:3
        methods = {'zoh', 'matched', 'tustin'};
        method  = methods{mi};
        labels  = {'zoh', 'matchedz', 'tustin'};
        label   = labels{mi};

        [b_d, a_d, y_step] = bw_design(ord, fc, fs, method);
        sname = sprintf('bw_%s_N%d', label, ord);
        emit_struct(fid, sname, ord, b_d, a_d, y_step);
    end
end

% ── Elliptic LP, orders 2–12, all three methods ──────────────────────────────

fprintf(fid, '// Elliptic lowpass: fc=100 Hz, fs=1000 Hz, Rp=0.5 dB, Rs=40 dB\n\n');

Rp = 0.5;
Rs = 40;

for ord = 2:12
    for mi = 1:3
        methods = {'zoh', 'matched', 'tustin'};
        method  = methods{mi};
        labels  = {'zoh', 'matchedz', 'tustin'};
        label   = labels{mi};

        [b_d, a_d, y_step] = el_design(ord, Rp, Rs, fc, fs, method);
        sname = sprintf('el_%s_N%d', label, ord);
        emit_struct(fid, sname, ord, b_d, a_d, y_step);
    end
end

fprintf(fid, '} // namespace acc_ref\n\n');
fprintf(fid, '#endif // CONSTFILT_PROFILING_ACCURACY_REFERENCE_HPP\n');
fclose(fid);

fprintf('Written: %s\n', outfile);
