name: ci

on:
  push:
    branches: [develop, main]
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check formatting
        run: make check-format

  build-and-test:
    name: ${{ matrix.compiler }}
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: read
      contents: read
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout consteig dependency
        run: git clone --depth=1 --recurse-submodules https://github.com/mitchellthompkins/consteig ../consteig

      - name: Build and test
        run: make test.${{ matrix.compiler }}
